### PR TITLE
Updates fuel icon

### PR DESCRIPTION
**Pull request by emilymdubois**
@natslaughter I'm at a bit of a sticking point with the fuel icon. I removed the numbers and rounded out the edges to align with perfect circles. After adding some space between the nozzle and the tank, it almost looked like a vacuum cleaner, so I tried to make the hose a little more distinctive.

I feel like there may be 2 outstanding issues:
- [ ] The nozzle shape is a little nondescript, but the original angular shape looked a little too bulky to me
- [ ] The hose looks a little fuzzy to me in the 11px version; we could get rid of the second "kink" but I was unsure how important it is to make the overall shape consistent between the 11px and 15px versions

Any advice or feedback is appreciated!

### CODE REVIEW

**Comment by natslaughter** [comment]
@emilymdubois,

These look great!
Unless you want to take a stab at refining the nozzle shape, these are ready to merge.

**Comment by emilymdubois** [comment]
@natslaughter I made some slight modifications to the nozzles. They feel better to me, but I'd love to hear your thoughts.

It looks like Travis is getting hung up on a few icon files that are saved as `<icon_name>-11-01` instead of `<icon_name>-11`. It also looks like there may be some icons -- `veterinary-15`, for example -- that have multiple paths in the SVG.

We can either fix these in this branch before we merge into `maki-2.0`, or we can go ahead and merge with failing Travis tests and fix on a new branch post-merge.

**Comment by natslaughter** [comment]
@emilymdubois I like the new nozzle. If it looks okay, can you round off the nozzle stroke ending? 

Let's go ahead and fix this branch before merging. This would be a great git exercise for me, so could we fix it together?

**Comment by emilymdubois** [comment]
Merge city 🌆 

For posterity, @natslaughter and I decided that we will cut a new branch from `maki-2.0` when all the icons are finished and fix all the Travis complaints

**Pull request merged**
