### PR TITLE
SVG cleanup

### PR DESCRIPTION
**Pull request by ajashton**
- consistent usage & styling of hidden canvas `<rect>`, with tests
- plain SVGs to get rid of unneeded Inkscape/Adobe properties

cc @springmeyer @samanpwbb

### CODE REVIEW

**Comment by springmeyer** [comment]
Looks like an excellent cleanup. I guess the next question is what ways we can test this to ensure rendering is still the same? Because currently Studio does not suffer from the temporarily Mapnik bug: one easy step would be checking a bunch of Studio styles with these new SVG.

**Comment by ajashton** [comment]
Here is a test with the cleaned SVGs https://api.tiles.mapbox.com/v4/aj.52358f75/page.html?access_token=pk.eyJ1IjoiYWoiLCJhIjoiRXVtT2dXRSJ9.sqsuB_uHGUlTXIi63-uYJA#14/41.8721/-87.6282

- z14 = 12px icons @ width=12
- z15 = 12px icons  @ width=24
- z16 = 18px icons @ width=18
- z17 = 18px icons @ width=36
- z18 = 24px icons @ width=24
- z19 = 24px icons @ width=48

**Comment by springmeyer** [comment]
Great, looks good. I updated the `place-of-worship-24.svg` and re-ran in the mapnik visual tests and see that the bbox for collision changed slightly (the red is the `DebugSymbolizer`). You'll need to open them both in tabs and flip back and forth to be able to see the minor difference. This seems acceptable and not a problem:

Before:

marker-svg-empty-g-element-500-100-2 0-agg-reference

After:

marker-svg-empty-g-element-500-100-2 0-agg

**Comment by ajashton** [comment]
I'm guessing this is correct. The original canvas boxes were drawn in Inkscape, and despite snapping to the grid were still slightly off sometimes. I just checked and the old place-of-worship-24 has a height of `24.000017`.

**Comment by ajashton** [comment]
In my style I forgot to test with `marker-fill`. No background box issues but it's raising issues with a few of the icons that don't use actual strokes for their outline. I'll fix these as well.

https://api.tiles.mapbox.com/v4/aj.52358f75/page.html?access_token=pk.eyJ1IjoiYWoiLCJhIjoiRXVtT2dXRSJ9.sqsuB_uHGUlTXIi63-uYJA#14/41.8897/-87.6280

**Comment by springmeyer** [comment]
> a few of the icons that don't use actual strokes for their outline

Interesting - before fixing can you capture an example of one of these - I want to make sure I have good testcoverage for before/after maki changes and before/after mapnik changes.

**Comment by ajashton** [comment]
The entrance icon is an example. The outline was handled by a buffer, not a stroke. So with a `marker-fill` style applied the outline became blue too.



- [old](https://github.com/mapbox/maki/blob/b504e07f82d5e08a43efab08add62820ebef15c6/src/entrance-18.svg)
- [fixed](https://github.com/mapbox/maki/blob/bcbd0d02fe8f9c367ff0b452dfbdf6c58348ede7/src/entrance-18.svg)

**Pull request merged**
