### PR TITLE
Snowmobile icons

### PR DESCRIPTION
**Pull request by sbtn**
Hi, I made some snowmobile icons for a map I am working on. If they are interesting for the icon set then I would like to add them.

Just let me know of any changes to be made.

### CODE REVIEW

**Comment by natslaughter** [comment]
Greetings @sbtn !
Thanks so much for the snowmobile contribution!!
They look great! I think they are very close to being finished. Here is some feedback for you:

snowmobile-15 1

snowmobile-15 2

snowmobile-11 1

snowmobile-11 2

Looking forward to seeing your progress!

**Comment by natslaughter** [comment]
@sbtn thanks for the update!
we are curious to see what the icon might look like without the human figure, and wonder if removing it would make the snowmobile's silhouette more unique.

**Comment by sbtn** [comment]
Hi @natslaughter and thanks for the feedback!

I opened up the space behind the ski on the snowmobile-15 as per your feedback and I agree that looks cleaner. 

I moved the rider back 1px on the snowmobile-11 also and even lowered 1px. I agree this also improved the clarity and proportions. I was concerned about also lowering the snowmobile-15 rider as it may lower the readability of the arm/hands. Let me know what you think and if the proportions should be more consistent between the different icon sizes.

Regarding the misalignment, I found that some features jumped out of place after the export from .ai to .svg format. I ended up changing the 'decimal place' option in the export to **4** - for the 15px icon and **3** - for the 11px. This increases the file size slightly but hopefully should be better aligned!

**Comment by sbtn** [comment]
@natslaughter I see your previous comment got in before I had finished mine :) I can do a revision without the rider.

**Comment by sbtn** [comment]
@natslaughter the latest revision has the human figure removed without any other alterations. If this is the style you are looking for then I think i could try to enhance the form of the snowmobile a little to work better alone.

In most of my cases the icon will be used to mark out particular snowmobile trails. As this is often considered an activity I felt it suitable to depict the icon with a rider. There are cases where the icon may be used for singular snowmobile friendly points of interest (gas stations, repair shops or drive-in's with snowmobile access) for which I would agree that the riderless icon is well suited.

**Comment by natslaughter** [comment]
@sbtn thanks for sharing the riderless snowmobile version. Without the rider, additional enhancements to the snowmobile form might be necessary: I'd be curious to see what you would propose!

**Comment by sbtn** [comment]
@natslaughter I altered the base snowmobile form a little bit now without the rider. 

I came to two different style alternatives which you can judge depending on what might work best in the icon set. I haven't revised the code but hopefully you can see from this attached image at 100% scale. 

I think the A. set represents a sportier model with a little tail and the B. set represents a classic, touring model with a pack box on the back.
snowmobile-15_11_a_b

Looking forward to your input on these revisions!

**Comment by natslaughter** [comment]
Thanks for the updates @sbtn !
I think the sportier model (A) works well. In fact, both work, but option B at 15x15 pixels seems a bit off. It seems that the back of the snow-mobile should be more tapered towards the snow-mobile body. The 11x11 pixel option B does this very well.

**Comment by sbtn** [comment]
Hi @natslaughter and thanks for the feedback. If I understood correctly then the icon pair (A) is preferred and the revision committed for further checks.

**Comment by natslaughter** [comment]
@sbtn Yes, option A looks like the best option.

**Comment by sbtn** [comment]
@natslaughter Great! Did you have any other comments or adjustments to be made for the latest  commit?

**Comment by natslaughter** [comment]
Hello @sbtn : not at this time. Go ahead and push your .svg files and I'll take a look at them. Thanks!

**Pull request merged**
