### PR TITLE
sports & leisure icons

### PR DESCRIPTION
**Pull request by rasagy**
Starting a PR to share svg files + track svg shape related progress that’s not possible in issues.

### CODE REVIEW

**Comment by rasagy** [comment]
First stab at adding some of these on a map (5 icons, names that aren’t direct/related to the maki icon) in four images (11 px and 15 px separately, two locations with different basemap):

atlanta z14 - generic - 11-v0 1
atlanta z14 - generic - 15-v0 1
ny z17 - generic - 11-v0 1
ny z17 - generic - 15-v0 1

cc @natslaughter

**Comment by rasagy** [comment]
Set 2:

atlanta z14 - generic - 11 copy-v0 2
atlanta z14 - generic - 15 copy-v0 2
ny z17 - generic - 11 copy-v0 2
ny z17 - generic - 15 copy-v0 2

**Comment by natslaughter** [comment]
per chat with @rasagy we are going to mock up the sports & leisure icons in these places:

Venice Beach, CA : beach, viewpoint, skateboard (skate-park)
Central Park, NY: basketball, tennis, table tennis, volleyball, slipway

**Comment by rasagy** [comment]
Testing these on Central Park, NY & Venice Beach, LA

ny - 15-v0 5
la - 11-v0 5
la - 15-v0 5
ny - 11-v0 5

**Pull request merged**
