### PR TITLE
archeological site

### PR DESCRIPTION
**Pull request by valleyofdawn**
First test at conforming to the maki guideline. 11 pt icon to follow.
Still need to get rid of extra stuff in the svg.

### CODE REVIEW

**Comment by valleyofdawn** [comment]
I've synched the 11 pt version of the archeological site. Also waterfall at
15 and 11. Would like your graphical design input before I upload more.

**Comment by samanpwbb** [comment]
Hi @valleyofdawn, thanks for adding the additional icons! A few notes:

- It will be much easier to get your work merged if you submit a separate PR for each icon
- Make sure your tests pass – you can run them locally with `npm install` and then `npm test`. 
- You need to add the icons you're adding to maki to the layout file here: https://github.com/mapbox/maki/blob/master/layouts/all.json which can be done automatically by via `npm run build`.

**Comment by valleyofdawn** [comment]
Dear Saman
I'm new to all this.
I didn't get half of what you wrote me.
Can we talk?

**Comment by samanpwbb** [comment]
@valleyofdawn sure! Email me and we can talk through the details.

**Comment by natslaughter** [comment]
@valleyofdawn 
Thanks for the icon submissions!!
It would be helpful to give you feedback on your icon designs if you could create separate pull requests for each icon. Once you do this, I will go through each pull request and provide feedback. 

cc @samanpwbb

**Comment by valleyofdawn** [comment]
Dear Nathaniel,

I've now submitted some of my icons is separate pull requests from separate
branches.
Would love to get your feedback.
I've been in touch with Saman as well.

-- 
Guy Shakhar
Associate Professor, Immunology Dept.
Weizmann Institute, Rehovot 76100, Israel.
shakhar@weizmann.ac.il
www.weizmann.ac.il/immunology/Shakhar
Tel:   +972-(0)8-934-3633
Cell:  +972-(0)52-583-1805

**Comment by valleyofdawn** [comment]
Please let me know if all the PRs went through.  I haven't heard anything
in a week.

בתאריך 15 בנוב׳ 2016 19:56,‏ "Nathaniel Garnett Slaughter IV" <
notifications@github.com> כתב:

**Comment by samanpwbb** [comment]
Hi @valleyofdawn! it looks like you have some test failures to resolve. You can view the test failures here: https://travis-ci.org/mapbox/maki/builds/176056785

**Pull request closed without merging**
