### PR TITLE
Historic icon

### PR DESCRIPTION
**Pull request by Udobnyj**
Adding a Historic icon. Closes https://github.com/mapbox/maki/issues/561

historic

### CODE REVIEW

**Review by tristen — CHANGES_REQUESTED** [review]
I think the concept is perfect! A couple of things:

- It looks like `browser.cjs.js` and `browser.esm.js` were unintentionally committed?
- Can you add a link to a demonstration? ([here's an example PR](https://github.com/mapbox/maki/pull/552)). It would be good to mimic how we use Maki in Streets today by adding a stroke using https://labs.mapbox.com/maki-icons/editor/
- Small nit picky things:

These extra anchors look unnecessary:
Screen Shot 2022-03-22 at 9 40 09 AM

The `y` coordinates on the stem could be rounded to the nearest integer. Also, does it look too thin if you just use a 1px stroke for the bottom stem?

Screen Shot 2022-03-22 at 9 40 05 AM

**Comment by Udobnyj** [comment]
@tristen 
Hey! Thank you for your comments!

First, about unnecessary anchors, remember I had an issue with lines, and I dealt with it only exported icon without flattening it. 
Screen Shot 2022-03-22 at 17 35 15

These anchors were created automatically. I tried to delete them, but lines issue came back 😓

Second, about coordinates. 
I tried the 1px option, but it looks too thin to me.
Here is how it looks on the maps:
options

And I added it to the studio.
[1px leg historic sign](https://api.mapbox.com/styles/v1/udobnyi/cl0jkhsbb001k14ldn1nx0sl2/draft.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#19.08/37.7627819/-122.4642921)
[1.5px leg historic sign](https://api.mapbox.com/styles/v1/udobnyi/cl12adkju002j14pcnw2a60d2/draft.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#20.02/37.759042/-122.4694493)

Still feels like 1,5px leg working better. But maybe there is no different? What do you think?

Anyway, if we decide to be so strictly grid-bound, I have a question. I looked at our actual icons, and I will say that they often deviate from our guides, both in line thickness and dot placement. Few examples:
Screen Shot 2022-03-22 at 16 31 48

Maybe I should then take over the task and fix it all?

**Comment by Udobnyj** [comment]
We discussed with @tristen  and decided to make a thin leg. 
All unnecessary anchors were removed, an icon was rechecked.

Screen Shot 2022-03-23 at 10 59 26

**Review by tristen — APPROVED** [review]
👏 it's great!!

**Pull request merged**
