### PR TITLE
Add monument-JP

### LINKED ISSUE #506: localized monument
inspo:
Screen Shot 2021-01-19 at 4 15 29 PM 

improve localization via creation of `monument-JP`

### PR DESCRIPTION
**Pull request by vknoppkewetzel**
## Description of change

Add localized monument icon for Japan

Inspiration:
Screen Shot 2021-03-03 at 11 23 24 AM

icon to be added:
Screen Shot 2021-04-14 at 10 30 29 AM

### Link to demonstration

Test style [here](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#15.25/38.889187/-77.044963)

---

Closes #506 

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [ ] Icon stays within a 2px trim area 
  --> I made an exception here and the top has just 1 px, in order to allow the monument to have height
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [ ] Any strokes use 1px
  --> the JP icons are 2px strokes, to match with the already existing JP icons that I looked at before making this JP set
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually
  - [x] add to test style

### For reviewer

- [ ] Review the interactive map provided to confirm legibility and harmony with existing icons
- [ ] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [ ] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [ ] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Comment by vknoppkewetzel** [comment]
Hey @tristen, this monument PR is now g2g for review with the new template ✨

**Review by tristen — CHANGES_REQUESTED** [review]
We should avoid these anchor points not landing on the nearest pixel. Can you make the icon narrower to avoid this?

Screen Shot 2021-04-14 at 11 53 37 AM copy

---

Avoid anchor points landing on coordinate floats. Bring this all up to the nearest pixel

Screen Shot 2021-04-14 at 11 53 51 AM

---

**Comment by vknoppkewetzel** [comment]
Thank you @tristen! 🙏  Have adjusted accordingly

**Comment by tristen** [comment]
@vknoppkewetzel can you just fix this up?

Screen Shot 2021-04-16 at 12 14 36 PM

**Comment by vknoppkewetzel** [comment]
@tristen oh gosh sorry, updated that as well now

**Review by tristen — APPROVED** [review]
🥇

**Pull request merged**
