### PR TITLE
`racetrack-cycling`

### PR DESCRIPTION
**Pull request by tristen**
## Description of change

Adds `racetrack-cycling` which is supported under `maki_beta` values in Streets v8

### Link to demonstration

https://api.mapbox.com/styles/v1/tristen/ckpio9qjr37sr18pqxmldy0zr.html?fresh=true&title=view&access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJjajZoOXU4Z2kwNnppMnlxd2d6bTFvZ2xtIn0.PP7AoUakMfeqdXFHdsY0oA

---

Ref #471

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [x] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [x] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [x] Review the interactive map provided to confirm legibility and harmony with existing icons
- [x] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [x] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [x] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Review by ClareTrainor — COMMENTED** [review]
Looking really good Tristen! 🚴  Just a few comments:  

1. Is it intentional that the wheels are different pixel widths? 
2. I see a few spots where this doesn't fully align to the half or full pixel grid. Does it work to shift the shoulder and arm up? 
Screen Shot 2021-06-12 at 2 55 53 PM

**Comment by tristen** [comment]
> Is it intentional that the wheels are different pixel widths?

It's intentional! It's supposed to mimic the rear wheel often looking different on track bikes 



That said, that isn't always the case and for less visual guesswork it might be simpler to make them both stroke width.

> I see a few spots where this doesn't fully align to the half or full pixel grid. Does it work to shift the shoulder and arm up?

👍 Will tweak this.

**Comment by tristen** [comment]
👋 @ClareTrainor back to you. I decided to make the back wheel filled in as it felt like it needed a higher degree of separation from `bicycle-share`

**Review by ClareTrainor — APPROVED** [review]
LGTM! I like the fill for the back wheel. Can you also check that you can open the icon in Illustrator? I was having some errors and I would like to confirm that designers can open the icon in any graphics application. https://labs.mapbox.com/maki-icons/guidelines/

Screen Shot 2021-06-15 at 3 12 30 PM

**Comment by tristen** [comment]
Ah! thanks for the catch @ClareTrainor I think I minified a bit too aggressively from https://jakearchibald.github.io/svgomg/. It should work as expected from Illustrator now:

Screen Shot 2021-06-16 at 10 17 13 AM

**Pull request merged**
