### PR TITLE
Update library icon

### LINKED ISSUE #504: Update library icon
`Library` icon update to  Screen Shot 2021-01-20 at 1 49 34 PM

### PR DESCRIPTION
**Pull request by vknoppkewetzel**
Closes #504 

Screen Shot 2

**Test style** [here](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#15.83/38.888776/-77.004273)

### CODE REVIEW

**Comment by vknoppkewetzel** [comment]
I removed -11 when I just updated the other tickets, which I believe is causing this to fail at the moment (but will be fine once we update requirements). Let me know if I should add -11 back in.

**Comment by tristen** [comment]
@vknoppkewetzel size adjustments look great! Just a couple points of feedback:


| Line up nodes to the pixel grid | Simplify some detail |
| --- | --- |
| I see some nodes that could be either be adjusted to the nearest pixel or 0.5 pixel. | At higher resolution, some nodes that break up the arc look a tad awkward. I'm seeing a couple places where it might be worth removing nodes and just rely on the arcs? |
| Screen Shot 2021-03-25 at 12 24 21 PM | Screen Shot 2021-03-25 at 12 21 54 PM |

**Comment by vknoppkewetzel** [comment]
Thanks @tristen done! 

For the grid alignment, I utilized "snap to grid" and snapped corners to grids (via highlighted the x # of nodes for each corner), and then turned snap off and moved 0.5 pixel for the ones that were applicable across the icon. Some are aligned to exact grid line

Let me know if this looks better to you. I made sure to move based on cluster of nodes as I wanted to make sure the angle relationship stayed the same.

**Comment by tristen** [comment]
yay! @vknoppkewetzel just one small nitpicky change: Can you pull these nodes down to the nearest 1 or 0.5 pixel?

Screen Shot 2021-03-29 at 12 17 17 PM

I did that quickly in Figma here:

Screen Shot 2021-03-29 at 12 23 13 PM

And I think it results in a more pronounced curve and crisper line at 100% resolution.

**Comment by vknoppkewetzel** [comment]
Thanks @tristen ! updated ✅

**Review by tristen — APPROVED** [review]
Beauty!

**Pull request merged**
