### PR TITLE
`racetrack-horse`

### PR DESCRIPTION
**Pull request by tristen**
## Description of change

Adds `racetrack-horse` which is supported under `maki_beta` values in Streets v8

### Link to demonstration

https://api.mapbox.com/styles/v1/tristen/ckpiogazi36bx18pg34ty1do4.html?fresh=true&title=view&access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJjajZoOXU4Z2kwNnppMnlxd2d6bTFvZ2xtIn0.PP7AoUakMfeqdXFHdsY0oA

---

- Ref #471

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [x] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [x] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [x] Review the interactive map provided to confirm legibility and harmony with existing icons
- [x] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [x] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [x] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Review by ClareTrainor — COMMENTED** [review]
Hold your horse, this new icon is wonderful! 🐴 This visually works well with the `horse-riding` icon and in the interactive map. 

- Main comments would be to look at where some of the points are placed. Does the shape hold when you slightly move these?
Screen Shot 2021-06-15 at 10 45 03 AM

**Comment by tristen** [comment]
@ClareTrainor Thanks for the review. Back2you

**Review by ClareTrainor — APPROVED** [review]
Changes look good! The only subjective design feedback I have is perhaps dropping the height of the rider by a pixel. Feel free to use your judgment here as both work well. 

Screen Shot 2021-06-16 at 12 54 52 PM

**Comment by tristen** [comment]
Hmm thanks for the feedback @ClareTrainor. I made it shorter:

Screen Shot 2021-06-16 at 8 43 36 PM

But at scale if feels pretty short compared to the other Maki icons. I'm realizing now that I made it a bit taller to feel a bit more balanced with other icons that feature a human like `bicycle-share` and `racetrack-cycling`. I think I'm inclined to keep it as is.

**Pull request merged**
