### PR TITLE
updating car-related icons

### LINKED ISSUE #528: update car-related icons
#### Icon Request
- Modernize car-related maki icons
- Related:
#524  
#522
#519  

icons_update_maki_2

### PR DESCRIPTION
**Pull request by willymaps**
## Description of change

These updated icons attempt to modernize the aesthetics of our auto-related maki icons.

There are three icon updates in this PR `car.svg`, `car-rental.svg`, and `car-repair.svg`. These will also align with the newly created `road-accident.svg` icon.

### Link to demonstration

[LINK](https://api.mapbox.com/styles/v1/william-davis/ckmv2b4hc04e617qc02p3aurc.html?fresh=true&title=view&access_token=pk.eyJ1Ijoid2lsbGlhbS1kYXZpcyIsImEiOiJja2prYmpvMncwM21pMnJtbjg0NnBjbWduIn0.9n0cpRnRO06AI7oydrZjbw)

Closes #528.

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [ ] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [ ] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [x] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [ ] Review the interactive map provided to confirm legibility and harmony with existing icons
- [ ] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [ ] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [ ] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Comment by willymaps** [comment]
Comparison with existing car icons:

icon_post_oldnew

**Review by tristen — CHANGES_REQUESTED** [review]
Looking good! Some small points of feedback:

| Anchor point bump | Extra anchor points | Snap to nearest pixel | Snap to nearest pixel |
| --- | --- | --- | --- |
| Just seeing this with `car`! could be an glitch when exporting |  It would be great to lessen on the number of anchor points that make up the rounded corners. | Looks like the wrench opening is slightly offest from the nearest pixel | Same here. |
| Screen Shot 2021-03-30 at 4 26 31 PM | Screen Shot 2021-03-30 at 4 27 02 PM | Screen Shot 2021-03-30 at 4 27 02 PM copy | Screen Shot 2021-03-30 at 4 27 36 PM |

**Comment by willymaps** [comment]
Thanks for the feedback! I updated 3/4 points from above. For the number of anchors on the wrench in `car-repair`, I'm only seeing the necessary amount in Illustrator. Possible Illustrator -> Figma issue?

image

**Review by tristen — APPROVED** [review]
🥨 wunderbar!

**Pull request merged**
