### PR TITLE
New Icon Batch Request

### PR DESCRIPTION
**Pull request by YunjieLi**
Add icons for landmark, karaoke, and gaming/internet cafe.

Landmark is conceptually similar to monument but with visuals for the Asian context

### CODE REVIEW

**Comment by natslaughter** [comment]
@YunjieLi 
Here is some feedback on the icons you're working on. Thanks so much for the help! 
Overall, I think they are shaping up nicely! Nice Job!

_Landmark_
Landmark-15 Looks great: pixel aligned and very crisp

Landmark-11's roof seems a bit off the pixel grid though:
landmark-11 1

landmark-11 2

_Karaoke_

The hand held mic is working as a concept, however the negative space in between the handle and the mic could be exaggerated a bit for more space. Also, the mic cord is different for each version, and I wonder if the difference is necessary. 

karaoke-15 1

karaoke-15 2

karaoke-11 1

karaoke-11 2

_Teahouse_

teahouse-15 1

teahouse-15 2

teahouse-11 1

teahouse-11 2

_Residential Community_

residential-community-15 1

residential-community-15 2

residential-community-11 1

residential-community-11 2

_Gaming_

I'm not convinced this icon concept is the best, but I'm certainly no gamer. 

gaming-15 1

gaming-15 2

gaming-11 1

gaming-11 2

**Comment by YunjieLi** [comment]
Thanks for the great feedbacks @natslaughter !

All the icons above are now in full pixels except for: tree trunk of residential-11, upper negative strip in karaoke both, and buttons in gaming-15.
I think the former two won't affect readability too much. I was not completely satisfied w/ gaming but this is the best I have so far.
image

**Comment by natslaughter** [comment]
@YunjieLi 
I like your building!

I had one comment on the central-building icon. The .5 pixel windows aren't showing up at 100% scale, so they might need to be 1 pixel or more in width. This might mean your building design will need changing in order to house the windows. 

central-building-15 1

central-building-15 2

central-building-11 1

central-building-11 2

**Comment by natslaughter** [comment]
@YunjieLi 
Regarding the gaming icons, they are looking great! 

The only thing is the buttons are still struggling to be clear at 100%.

screen shot 2016-09-01 at 2 43 34 pm

screen shot 2016-09-01 at 2 44 20 pm

I think there still might be too much detail for such a small icon. The circular buttons that are taking up 1 pixel are still being greyed since the edges of the pixel consist of black. And the buttons on the 15 pixel are off the pixel grid, so they are greyed as well. Check it out in the pixel preview:

screen shot 2016-09-01 at 2 47 33 pm

You could try making the buttons square to avoid this and see what that looks like. 

That said, they look great at this scale!

screen shot 2016-09-01 at 2 48 53 pm

Another thing: these icons switch from the 11px and 15px versions depending on map zoom levels, so it really helps to have the geometries as similar as possible for smooth transitions. In this case, it might be worth making the cords the same, as cool as they are. 

One last thing: At 100%, it's hard to tell what these objects are. Is there a way to make their silhouette more unique? And don't be afraid of scrapping this idea and coming up with a different icon concept.

**Comment by YunjieLi** [comment]
Just redrew gaming-11, -15 to hopefully create a stronger silhouette. I still couldn't accept square buttons😂

image


image

@natslaughter

**Comment by natslaughter** [comment]
Table showing the final designs of this batch of icon requests.

|Name |11px | 15px | 
|:--- |:---- |:----| 
|blood-bank| blood-bank-11-01 | blood-bank-15-01 | 
|buddhist| buddhism-11-01 | buddhism-15-01 | 
|central-building| central-building-11-01 | central-building-15-01 | 
|gaming| gaming-11-01 | gaming-15-01 | 
|karaoke|   |   | 
|landmark| landmark-11-01 | landmark-15-01 | 
|residential-community| residential-community-11-01 | residential-community-15-01 | 
|teahouse| teahouse-11-01 | teahouse-15-01 | 

@YunjieLi @andreasviglakis @samanpwbb @nickidlugash

**Comment by natslaughter** [comment]
Per chat with @nickidlugash, here are some final edits and thoughts regarding this batch of icons.

_Bloodbank_
- [ ] Vertically compress 15px icon 1 pixel to match the overall shape of the 11px version

_Central Building_
- [ ] Make ground plane .5 pixels instead of 1 pixel.

_Karaoke_
- [ ] Round out the 11px mic top. It appears flat and produces a point in the top right corner. 

_Landmark_
- [ ] Extend the 11-pixel icon base outwards 1 pixel, to align with the roof.
- [ ] To be consistent with other Maki icons, round base corners to a radius of 1 pixel. 

_Teahouse_
Not sure if this icon concept is working: It almost reads more like a plant.  
- [ ] Exaggerate the cup base 1 pixel in height. The base doesn't read at 100% on non-retina screens. 
- [ ] Try a different icon concept: Enlarge the cup and have a single tea leaf as negative space within the cup geometry. 
- [ ] Try a different icon concept: Tea kettle.  

@YunjieLi

**Comment by samanpwbb** [comment]
\o/

**Comment by andreasviglakis** [comment]
> \o/

\o/

**Comment by tristen** [comment]
>> \o/

>\o/

\o/

**Pull request merged**
