### PR TITLE
add lighthouse-JP

### LINKED ISSUE #507: localized lighthouse
create localized lighthouse icon for Japan 

inspo 
 Screen Shot 2021-01-19 at 4 15 56 PM

### PR DESCRIPTION
**Pull request by vknoppkewetzel**
## Description of change

Add localized lighthouse icon for Japan

inspiration: 
Screen Shot 2021-03-03 at 4 05 56 PM

new icon:
Screen Shot 2021-04-14 at 10 25 27 AM

### Link to demonstration

test style [here](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#17/41.248827/-72.903123)

--- 

Closes #507 

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [x] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [x] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [ ] Review the interactive map provided to confirm legibility and harmony with existing icons
- [ ] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [ ] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [ ] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Comment by vknoppkewetzel** [comment]
updates, Working on updating this to rounded corner version

Screen Shot 2021-04-13 at 4 59 03 PM

**Comment by vknoppkewetzel** [comment]
Screen Shot 2021-04-14 at 10 25 27 AM

Did some reworking of it, when looking at the Maki Editor again, I noticed the `religious-buddhist` icon is a similar shape so I used that as a starting template instead

**Comment by vknoppkewetzel** [comment]
Hey @tristen, this PR is now g2g for review with the new template ✨

**Comment by tristen** [comment]
@vknoppkewetzel thoughts on increasing the points sticking out? They read pretty thin on the map:

Screen Shot 2021-04-14 at 12 08 00 PM

If they are supposed to communicate light casting out from the circle it might make sense to bring them out to the nearest pixel:

Screen Shot 2021-04-14 at 12 10 03 PM

**Comment by vknoppkewetzel** [comment]
Great idea @tristen  ! Have adjusted accordingly

Screen Shot 2021-04-16 at 11 32 43 AM
to Screen Shot 2021-04-16 at 11 32 56 AM

**Review by tristen — CHANGES_REQUESTED** [review]
@vknoppkewetzel a bit more feedback!

Seeing some awkwardness here

Screen Shot 2021-04-16 at 12 32 28 PM

---

Thanks for lengthening the beams! Sorry to be picky but can we avoid the anchor points landing on a .5 pixel point and design to fit on a round pixel value?

Screen Shot 2021-04-16 at 12 36 06 PM

---

This is reading less like beams emitting from a central source and more like the helm of a ship

Screen Shot 2021-04-16 at 12 33 17 PM

Can we make the ring a little smaller to provide more room for the beams?

---

Finally! Can you update the interactive link after making updates? Helps to see the changes!

**Comment by vknoppkewetzel** [comment]
that's a good point it does look like a ship's steering wheel. I had initially made the circle smaller but worried the inner circle got lost a little, however i can go back to that and play with it. 

Happy to align not with a 0.5 pixel, and missed that imperfection. 

Will address after meetings, thanks so much for this detailed feedback. All of this across these symbols is helping me get a little more practice in my symbol-detail-analysis, I really appreciate the detailed feedback. 🙏

**Comment by tristen** [comment]
> I had initially made the circle smaller but worried the inner circle got lost a little, however i can go back to that and play with it.

Yeah, the inner circle has pretty good proportions. Maybe the outer ring?

**Comment by vknoppkewetzel** [comment]
@tristen yeah! I meant I had initially made the outer ring take up a smaller extent as well, but I will play around with it 🙏 some more, ty! It's good to get feedback on this one, I had a few iterations that I wasn't fully happy with so it's good to hear thoughts on it.

**Comment by vknoppkewetzel** [comment]
👋  @tristen  I have adjusted the icon, let me know if this looks good! [test style updated ](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#17/41.248827/-72.903123)

**Review by tristen — APPROVED** [review]
Yay! Approving to unblock but there's just some small irregularities on two bottom anchor points:

Screen Shot 2021-04-16 at 2 45 13 PM

**Comment by vknoppkewetzel** [comment]
@tristen gosh idk why that happens, this must relate to how the SVG saved decimal-wise. I have suspected Adobe Illustrator doesn't always preserve recent SVG save settings and this happening 2x times makes it confirmed so i will make sure to go through the full "Save As" in the future rather than just "Save"

Tysm for flagging!

**Pull request merged**
