### PR TITLE
Add highway-rest-area

### LINKED ISSUE #466: Highway rest area
`highway-rest-area` https://wiki.openstreetmap.org/wiki/Tag:highway%3Drest_area

### PR DESCRIPTION
**Pull request by melanieimfeld**
## Description of change

Adding a the `highway-rest-area` icon to `maki-beta` 

### Link to demonstration

[LINK](https://api.mapbox.com/styles/v1/imfeld/cko227oh0121218pfgt1fukse.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW1mZWxkIiwiYSI6ImNqMzR2aTE0dDAwaGYyd3Fncmc1ODRkemcifQ.HTl7csPq_0VP3yO28G2u8Q#16.68/35.842119/139.503551/-30.4/63)

---

Closes #466 .

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [ ] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [x] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [ ] Review the interactive map provided to confirm legibility and harmony with existing icons
- [ ] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [ ] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [ ] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### Additional comments for reviewer
As discussed in styles review, I started off with an option (see below) that adheres to the circular trim area and has a more "table-shaped" table. When placed in the map, the table and the base were very difficult to see.

**First version**
Screen Shot 2021-04-29 at 5 19 05 PM

Because of readability, I abandoned the above in favor of a version 1) with a more abstract table, 2) exceeding the circular trim area. It does still seem pretty small to me, so I do wonder if even more abstraction is needed?

**Selected version**
Screen Shot 2021-04-29 at 5 19 59 PM

### CODE REVIEW

**Comment by tristen** [comment]
Hmm @melanieimfeld I wonder if there's a balance between the first and selected versions? The square is reading as a park table to me and feels a bit disproportionate to the tree. I think there's room to increase the size of the icon slightly if space feels constrained to increase legibility? (it looks a [little smaller than the other Maki icons currently](https://api.mapbox.com/styles/v1/imfeld/cko227oh0121218pfgt1fukse.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW1mZWxkIiwiYSI6ImNqMzR2aTE0dDAwaGYyd3Fncmc1ODRkemcifQ.HTl7csPq_0VP3yO28G2u8Q#16.68/35.842119/139.503551/-30.4/63))

**Comment by melanieimfeld** [comment]
> Hmm @melanieimfeld I wonder if there's a balance between the first and selected versions? The square is reading as a park table to me and feels a bit disproportionate to the tree. I think there's room to increase the size of the icon slightly if space feels constrained to increase legibility? (it looks a [little smaller than the other Maki icons currently](https://api.mapbox.com/styles/v1/imfeld/cko227oh0121218pfgt1fukse.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW1mZWxkIiwiYSI6ImNqMzR2aTE0dDAwaGYyd3Fncmc1ODRkemcifQ.HTl7csPq_0VP3yO28G2u8Q#16.68/35.842119/139.503551/-30.4/63))

thanks for the feedback @tristen, let me try to scale up the first version then! The T-shaped table was really hard to read, but maybe I can make it visible by substantially scaling up

**Comment by melanieimfeld** [comment]
@tristen @vknoppkewetzel 
I updated the icon by scaling the first version to fit within a bounding box of 13px (see screenshot below or map demo [here](https://studio.mapbox.com/styles/imfeld/cko8ydozv2ha217s22lu324rz/edit/#15.07/35.84232/139.50572/39.2/62)) What do you think?
Screen Shot 2021-05-03 at 5 07 17 PM

**Comment by tristen** [comment]
@melanieimfeld these changes look great and extending some of the shapes outside the trim area makes sense to me 👍  I think there's some opportunity to draw some of these anchor points to the nearest pixel to increase legibility at smaller sizes:

Screen Shot 2021-05-04 at 9 14 44 AM



As example, compare the table vertical base (with anchor points on the nearest pixel) to the top of the table or tree trunk:

Screen Shot 2021-05-04 at 9 09 24 AM

More antialiasing is being applied which creates a bit of blurriness when the icon is rasterized.

**Comment by melanieimfeld** [comment]
@tristen I made some adjustments to the shapes to align to the pixel grid (Only the anchor points from the rounded tree corners are off grid, such that the outermost points touch the vertical pixel gridlines). Here's [the map view too](https://api.mapbox.com/styles/v1/imfeld/cko8ydozv2ha217s22lu324rz.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW1mZWxkIiwiYSI6ImNqMzR2aTE0dDAwaGYyd3Fncmc1ODRkemcifQ.HTl7csPq_0VP3yO28G2u8Q)!
Screen Shot 2021-05-04 at 12 48 36 PM

**Review by tristen — APPROVED** [review]
Looks great! 🏄

**Pull request merged**
