### PR TITLE
nat-updates

### PR DESCRIPTION
**Pull request by natslaughter**

### CODE REVIEW

**Comment by bsudekum** [comment]
@natslaughter it looks like this added `node_modules/`, maybe a mistake?

**Comment by natslaughter** [comment]
@bsudekum,
I'm not sure. Honestly, I am very green to Github and Command Line. In your 'vastly greater experience' opinion, what would you do?

**Comment by bsudekum** [comment]
@natslaughter there is no need to commit the node_modules folder since this is generated every time someone runs `npm install`. You can add `node_modules` to the [`.gitignore file`](https://github.com/mapbox/maki/blob/mb-pages/.gitignore). This way any time you run `git status` or stage files, this folder will be completely ignored.

**Comment by natslaughter** [comment]
@bsudekum,
That makes sense. Thanks for taking the time to explain that!

**Pull request merged**
