### PR TITLE
add ferry-JP

### LINKED ISSUE #508: localized ferry
Create localized ferry icon for Japan

inspo:
 Screen Shot 2021-01-19 at 4 22 21 PM

### PR DESCRIPTION
**Pull request by vknoppkewetzel**
## Description of change

Add localized ferry icon for Japan

Inspiration:
Screen Shot 2021-03-03 at 11 35 22 AM

icons look like:
Screen Shot 2021-03-03 at 12 14 00 PM

### Link to demonstration

test style [here](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#15.61/47.602369/-122.337888)

---

Closes #508

### For author

- [x] Cite changes under the `HEAD` tag in [`CHANGELOG.md`](../CHANGELOG.md)
- [x] PR contains only one 15x15 icon
- [x] Changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)
  - [x] Icon geometry is aligned to the pixel grid
  - [ ] Icon stays within a 2px trim area
  - [x] Icon uses common geometric building blocks used throughout Maki
  - [x] Icon corners are rounded in either full or half pixel increments
  - [ ] Any strokes use 1px
- [x] Upload the new icon to the [Maki icon editor](https://labs.mapbox.com/maki-icons/editor/)
  - [x] Compare with existing icons
  - [x] Test that stroke/backgrounds/padding work visually

### For reviewer

- [ ] Review the interactive map provided to confirm legibility and harmony with existing icons
- [ ] Review each icon variation in an editor, turn on grids and outlines and confirm pixel alignment is maintained to the nearest or half pixel
- [ ] Confirm file requirements stated in [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/) are met 
- [ ] Confirm all other changes fall in accordance to the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

### CODE REVIEW

**Comment by vknoppkewetzel** [comment]
👋 @tristen would you mind taking a look at this PR this week? also can reassign!

**Comment by vknoppkewetzel** [comment]
@tristen hrm thanks for pointing that out I had chosen Seattle as a location but looks like I did not save the copy-paste of the Seattle coordinates. It's updated now.

also have updated each ticket re: checklist, and will double check the checklists and ✅  things off today, to have them all ready for review ✨

**Review by tristen — CHANGES_REQUESTED** [review]
The shape and proportions look nice! Here's some minor feedback 

| Align shape to the pixel grid | Align anchor points to the grid | Remove superfluous anchor points |
| --- | --- | --- |
| The whole shape is floating off the nearest pixel which tends to look blurry when an icon that size is exported as raster and hinted. Ideally, the overall shape should be centered and adjusted slightly to the nearest pixel. | For simple anchor points like these, make sure their coordinates align to the nearest `0.5` or `1` values. | There are a couple of extra anchor points that could be omitted without affecting the shape of the icon |
| Screen Shot 2021-04-13 at 2 20 50 PM | Screen Shot 2021-04-13 at 2 21 08 PM | Screen Shot 2021-04-13 at 2 21 51 PM |

**Comment by vknoppkewetzel** [comment]
@tristen thank you for this feedback! The ferry icon has been updated. I decided to make an exception with the 2px trim area in order to still allow this icon to have height and look less "fat", let me know if that looks alright. 

test style also has been updated

**Review by tristen — CHANGES_REQUESTED** [review]
This is close! Just seeing some small inconsistencies where anchor point coordinates are off:

Screen Shot 2021-04-14 at 12 14 19 PM
Screen Shot 2021-04-14 at 12 14 30 PM

**Comment by vknoppkewetzel** [comment]
Hey @tristen, I have updated the anchor coordinate angle, thank you!

**Comment by tristen** [comment]
@vknoppkewetzel anchor points look nice! Thoughts on making this a tad smaller/within the trim area?  viewing this icon alongside monument, it's a little tall+wide

Screen Shot 2021-04-16 at 12 22 26 PM

**Comment by vknoppkewetzel** [comment]
@tristen definitely, with the changes with monument this also looks less similar. will align it better and update accordingly after meetings 🙏

**Comment by vknoppkewetzel** [comment]
Hey @tristen the [test style](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#15.61/47.602369/-122.337888) and icon have been updated, let me know what you think

**Comment by tristen** [comment]
@vknoppkewetzel ahh one small minor thing. What do you think about making it just 1px taller?

Screen Shot 2021-04-16 at 2 35 33 PM

**Comment by vknoppkewetzel** [comment]
@tristen yes, np, [done](https://api.mapbox.com/styles/v1/vkwetzel/ckmgatops1wvk17lbziuy5ui1.html?fresh=true&title=view&access_token=pk.eyJ1Ijoidmt3ZXR6ZWwiLCJhIjoiY2swNzNzamw3MDB6azNtcGVvN3cxNTJzZSJ9.YY56WOsc0ZNIK9YTwosnTw#15.61/47.602369/-122.337888)!

**Review by tristen — APPROVED** [review]
🚢

**Pull request merged**
