### PR TITLE
Add aerialway icon.

### PR DESCRIPTION
**Pull request by christoph-buente**
This icon can be used for several osm tags like

aerialway=cable_car
aerialway=gondola 

see: http://wiki.openstreetmap.org/wiki/Map_Features#Aerialway

### CODE REVIEW

**Comment by samanpwbb** [comment]
Can you commit an update to https://github.com/mapbox/maki/blob/mb-pages/_includes/maki.json as well?

**Comment by christoph-buente** [comment]
Sure. I rebased mb-pages again and ran all the dev-render steps.

**Comment by christoph-buente** [comment]
@samanpwbb Any more i can do to have this PR requested?

**Comment by samanpwbb** [comment]
Looks good :+1:

**Pull request merged**
