### PR TITLE
School icon

### PR DESCRIPTION
**Pull request by Udobnyj**
Based on [this almost endless task](https://github.com/mapbox/maki/issues/434)

### CODE REVIEW

**Comment by tristen** [comment]
👋 @Udobnyj I think you just want to include https://github.com/mapbox/maki/pull/573/commits/6782fd73817d0041140f1b40710f665f1a98cfed as part of this PR?

**Comment by Udobnyj** [comment]
@tristen Sorry! You right! Changed it! ❤️

**Comment by willymaps** [comment]
Looking great @Udobnyj.

Would it make sense to slightly alter the angle of the pencil and match the apple base?

**Current**

image

**Proposed**

image

**Comment by Udobnyj** [comment]
@willymaps changed it! 🙏

**Review by tristen — APPROVED** [review]
🍏

**Pull request merged**
