### PR TITLE
Toll booth icon

### PR DESCRIPTION
**Pull request by tjukanovt**
Adding a toll booth icon. Closes https://github.com/mapbox/maki/issues/500 

toll-booth

Icon has been designed following the [Maki guidelines](https://labs.mapbox.com/maki-icons/guidelines/)

How it looks with Mapbox Streets:
image

### CODE REVIEW

**Comment by willymaps** [comment]
☝️  once you have this the `undefined.svg` you no longer be generated.

**Comment by willymaps** [comment]
Hey @tjukanovt,

This looks really good. Just a couple suggestions:

1. @tristen made a good point about not rounding some of the corners. Would also make it consistent with the `highway-rest-area` icon

image

2. The toll booth arm should align to the closest pixel or half pixel

image

**Comment by tjukanovt** [comment]
Thanks a lot for the comment @willymaps. I think the edges are rounded in a much more logical way now and the arm is now aligned to the 1 px edge.

**Review by willymaps — APPROVED** [review]
Looks good to me 🪙

**Pull request merged**
