### PR TITLE
Recycling Icons

### PR DESCRIPTION
**Pull request by dasulit**
Put my geometry skills to the test for this ♻️

cc @samanpwbb @natslaughter

screen shot 2016-09-28 at 6 47 05 pm
screen shot 2016-09-28 at 6 47 33 pm

### CODE REVIEW

**Comment by samanpwbb** [comment]
@dasulit I will leave icon review to Nat – before we get there though, you have a few tests to fix up.


First of all, pull down my latest commit to this branch. 

Then, run the tests with `npm test`. 

You will see a few errors.

- Make sure all your icons are in the layout file by running `node ./scripts/make-layouts.js`.
- Make sure your SVG geometry is clean. Icons should consist of only a single path, no groups, no other geometry types.

Let me know if you have any questions.

**Comment by natslaughter** [comment]
Hi @dasulit !

Thanks for the Maki work.

To follow up on @samanpwbb's comments, your 15 pixel icon has some lines in it, instead of the icon being a single path. Both of your icons need to be a compound path. I can go over this in detail if you need later. 

_11 pixel_

recycling-11

at 100% scale, this icon looks a little blurry, and it's hard to decipher what exactly it is. The primary reason for this is pixel alignment, which will be a little tricky with this particular icon. Try to align the geometry as much as possible to the pixel grid. Another thing to experiment with that might help is diminishing the arrow stem width to .5 pixels. 

Here are some comments on the geometry details:

screen shot 2016-09-29 at 11 37 53 am


_15 pixels_

recycling-15

This one reads better at 100% scale, but might be able to get crisper with some minor shits that align the icon to the pixel grid. 

recyling1-15

Overall, it seems that all three of the arrows are subtly different, especially in the 11 pixel icon. Try drawing one arrow, then rotating it 120 degrees along a circle, with the rotation anchor in the center of the circle.

rotate-diagram

Let me know if you have any questions!

**Comment by dasulit** [comment]
Hey @natslaughter! Belated thank you for taking the time to give a detailed and thorough review. Getting the geometry right on this has been a task, and I'm not sure that there's a way to make this triangle truly pixel-perfect.. 🤔 

I'm coming back to this with a second take, and would love to hear what you think. The 15px version seems close to me, but the 11px version is still muddy.

screen shot 2016-10-26 at 6 14 45 pm

I created the bottom right arrow first, then rotated it along the circle, but I haven't been able to draw an arrow that still aligns to the pixel grid when rotated.

screen shot 2016-10-26 at 6 17 51 pm

screen shot 2016-10-26 at 6 18 10 pm

Looking forward to hearing your guidance on this! ❤️

**Comment by natslaughter** [comment]
per chat with @dasulit, Dana is going to try to massage each arrow to align more with the pixel grid, and see if this will make the icons more crisp without losing too much arrow uniformity.

**Comment by dasulit** [comment]
@natslaughter per our conversation, I made each arrow slightly unique to be more aligned to the pixel grid. Would love your thoughts on this most recent revision!

**Comment by natslaughter** [comment]
Updates to the recycling icon after some massaging and small adjustments. This iteration uses a one sided arrow in order to thin out the arrow head geometry. 

11-pixel

screen shot 2016-12-22 at 3 04 49 pm

15-pixel

screen shot 2016-12-22 at 3 05 13 pm

cc @dasulit

**Comment by dasulit** [comment]
Yay! Happy to see this PR brought back to life.

If it's helpful, this is where I had left off:

11px:
screen shot 2016-12-22 at 3 12 44

15px:
screen shot 2016-12-22 at 3 13 03

I think the one-sided arrow direction is a good one to explore, especially at 11px.

**Comment by aparlato** [comment]
@natslaughter this is reading really well. Is it possible in the 15px to get a tiny bit more white space between the arrows on the bottom of the triangle? If not, it's not a big deal.

**Comment by natslaughter** [comment]
@aparlato 
Took a stab at getting some more white space between the bottom arrows. 

11-pixel
screen shot 2016-12-23 at 2 04 05 pm

15-pixel
screen shot 2016-12-23 at 2 03 53 pm

cc/ @nickidlugash

**Comment by aparlato** [comment]
Hey @natslaughter I think I had a minor breakthrough with the recycling icon by cutting up a circle and rotating each of the pieces individually. I'm going to work on this more tomorrow, but let me know if you have some input from this jumpoff point that could help the arrow heads.

**lines with no arrows yet**
image image

**arrows not working yet**
image image

**Comment by aparlato** [comment]
I cleaned things up a bit on the last version, but it's still blurry due to where the angles and curves fall on the pixel grid.
image image

image image

**Comment by natslaughter** [comment]
@aparlato a few comments:

- I would be curious to see a version that has extended ends at a 90º angle. Maybe this might make the icon feel more like a triangle, similar to the ubiquitous recycling icon.
- I feel the arrow heads on the 11-pixel icon are too small, and get lost at 100% scale. I would try exaggerating them so they are differentiated from the arrow stem. 
- Do you feel that this alternative to the universal, triangular recycling icon is the direction to go? Do you have any versions of the triangular icon?

**Comment by aparlato** [comment]
@natslaughter I'll give these suggestions a shot. I do have renditions in the more common triangle, but nothing that ended up looking any different from your's and Dana's previous attempts.

I'm not 100% sure this is the way to go yet _but_ it definitely opens up some space and I think your suggestions might help bring back more familiarity.

**Comment by aparlato** [comment]
Just the 11px here right now. Showing a real quick rough of @natslaughter 's suggestions and I think it is actually looking pretty good. 

Going to go ahead and refine this now and create the 15px, but I wanted to ask what you all think about the way those '90deg' angles look off of the curved elements. Does this work with guidelines?

image image

**Comment by dasulit** [comment]
👋  @aparlato @natslaughter I'm happy to see these explorations here! Just wanted to offer my two cents: when I was spending time on this, I didn't feel that there was a problem aligning the arrow stems and elbows to the grid. Rather, the issue was with the rotated arrow heads. I would hesitate to move too far away from the classic triangular shape. Instead, I'm curious to see if you are able to come up with a creative solution to get the arrow heads on the pixel grid, which I hadn't yet arrived at myself! Let me know if I can jump back in and help in any way.

**Comment by aparlato** [comment]
@dasulit good point I totally agree. After much experimentation though, I'm at a loss for how to make the arrow heads pixel-align well, and have taken the approach of trying to do what gives the best general impression of a recycling symbol (at least trying to make the blurring relatively consistent).

As far as the triangle shape, does this refer to the latest post? I think @natslaughter 's suggestion above has helped a good bit to bring it back to a triangle, but maintaining the openness of the swirling circle segments I posted previously. Below is an updated/cleaned up version of my last post.

Do you think these are working or is a strict triangle really the only way to go?

**11:**
image image

**15:**
image image

**Comment by natslaughter** [comment]
@aparlato 
I think these latest iterations are working well, however, I find the arrowheads in the 11-pixel icon to get lost. Is there a way to make these arrowheads bigger, so to distinguish them from the stems, or does an increase in size encroach on needed whitespace? 

cc / @dasulit

**Comment by dasulit** [comment]
@aparlato this is quite a dynamic shape! At an enlarged size, the angles of the stems look a little funny, but they ends up looking really tight at their true size. I think a really big advantage of this approach will be that you're escaping the seemingly mutually exclusive constraints of being geometrically exact, and making a pixel perfect icon. IMO that leaves more room to play around to get the icon just right— definitely agree with @natslaughter that there needs to be a bit more constrast between arrow and stem width. Liking this direction a lot though!

**Comment by natslaughter** [comment]
@aparlato I was also admiring @dasulit's last iteration yesterday as I was struggling to figure this what this icon wants to be. If you think it's worth it, maybe starting an iteration based on Dana's last icon and see if it can be refined? 

Looking at the above icons (a,b,c,d), it seems that both increasing the arrowhead and spacing out the arrows is not working for this version at the 11-pixel scale. FWIW, the 15-pixel icon looks great!

One more thing to try out - maybe - is tapering the arrow stem and decrease its width as it moves towards the arrowhead.

**Comment by natslaughter** [comment]
@aparlato I think option A is looking promising. Is it possible to get any additional white space in between the arrows?

**Comment by aparlato** [comment]
image image

image image

cc @natslaughter

**Comment by dasulit** [comment]
Good stuff @aparlato! It looks like the leftmost arrow on the 15px version is ever so slightly off in the Y-direction. Could you try moving that arrow up the tiniest amount? Here's a quick screenshot of our experiment (your iteration is on the left, revised with a slightly adjusted leftmost arrow is on the right)

screen shot 2017-01-06 at 2 46 24

**Comment by aparlato** [comment]
@natslaughter @nickidlugash @dasulit good catch!

image
image
image
 changes pushed :+1:

**Pull request merged**
