### PR TITLE
changing parking icon

### PR DESCRIPTION
**Pull request by Udobnyj**
Adding a new Parking_paid icon and changing the old parking icon.
parking_paid parking
Created in this [task](https://github.com/mapbox/mapbox-core-style-icons/issues/238) 
Screen Shot 2022-06-17 at 17 32 32
Screen Shot 2022-06-17 at 17 32 42

### CODE REVIEW

**Comment by tristen** [comment]
@Udobnyj love the consistency of them! (great call redrawing `parking`). The dollar sign portion of `parking_paid` doesn't read very legibly to me:

parking_paid

- Could you add this to an example map to see how it looks? I would also be curious what this looks like behind a circle background.
- I wonder how well `$` translates in other countries to denote paid parking. What do you think about using a credit card with strip?

**Comment by Udobnyj** [comment]
@tristen, thanks a ton for the comments! 
Totally agree with all parking-paid ones.

Here is the parking-paid example on the map, and yes, because it's so tiny and doesn't fit the grid, it's not reading well.
Screen Shot 2022-06-21 at 13 14 44

[Studio map link](https://api.mapbox.com/styles/v1/udobnyi/cl3vegi7r000615tj4pkrth12.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#16.83/55.734081/37.60361)

I tried the card option, on the map it looks cleaner, but I'm not sure about metaphor. Is it clear? What do you think? 
Screen Shot 2022-06-21 at 14 27 55
Screen Shot 2022-06-21 at 14 27 28
[Studio map link](https://api.mapbox.com/styles/v1/udobnyi/cl3vegi7r000615tj4pkrth12.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#17.5/55.73376/37.60285)

**Comment by Udobnyj** [comment]
I'm still doubting about Parking with the card. A few times, I felt it was not a card but a burger (like a park and eat place). I even tried a few more options, but non of them aren't working as well as $ one.
Screen Shot 2022-06-22 at 11 24 40
l

**Comment by tristen** [comment]
> How about we keep the improved `parking` icon and drop `parking_paid` as a maki icon? Big cities seem to be moving away from the concept of free-parking, so I wonder if this specificity will even be relevant in these locations.

👍 Also throwing out there ... if we _do_ need to communicate paid parker vs not on maps that we can do that using a background color? Green = paid, Blue = free?

**Comment by Udobnyj** [comment]
Let's separate icons, then. 
In this PR, I left only **parking**, and we can continue discussing **parking-paid** icon in the task https://app.zenhub.com/workspaces/map-design-team-5ed96b144161fad651898382/issues/mapbox/mapbox-core-style-icons/238

**Review by willymaps — APPROVED** [review]
🅿️ ✅

**Pull request merged**
