### PR TITLE
Centering 38 maki icons

### PR DESCRIPTION
**Pull request by Udobnyj**
Based on [this task](https://github.com/mapbox/maki/issues/564), I adjusted 46 of our icons to work better with the background. 

I didn't change the vector. I just moved them inside the artboards. But six of them are not along the pixel grid but 0.5px: shelter, bowling-alley, basketball, ferry-JP, amusement-park, and religious-muslim. 

[MAIN STUDIO TEST LINK ](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#17.61/37.551883/-122.312378)

**Concreete 0.5px icons links** 
I didn't find *shelter*, *bowling-alley*, and *ferry-JP*, so I replaced the other icons.

[shelter](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#18.95/60.1784731/24.9298819)

[bowling-alley](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#17.92/55.770432/37.573119)

[ferry-JP](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#16.76/35.574531/139.785888)

 
[basketball](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#21.04/32.0045711/34.7987861)
 
[amusement-park](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#15.07/35.62538/139.88115)

[religious-muslim](https://api.mapbox.com/styles/v1/udobnyi/cl3o9dudb003n14pleewlov0e.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#17.69/31.778212/35.234657)

### CODE REVIEW

**Comment by Udobnyj** [comment]
I was thinking about 0.5px moved icons.
I think I have an idea of how to fix it. I can do it in this [task](https://github.com/mapbox/maki/issues/555). Along with sizing, I can adjust them to fit the pixel grid

**Comment by tristen** [comment]
@Udobnyj this is a little tedious, but could you share a map example with these icons using a background? Also perhaps a map example showing the before with backgrounds? Just to get a better sense of how centering these addresses visual inconsistency?

**Comment by tristen** [comment]
> But six of them are not along the pixel grid but 0.5px: shelter, bowling-alley, basketball, ferry-JP, amusement-park, and religious-muslim.

@Udobnyj we should avoid offsetting these to 0.5px just for centering and consider redrawing these instead?

Screen Shot 2022-05-30 at 10 46 51 AM

**Comment by Udobnyj** [comment]
I decided to revert ten icons (6 of those that I moved by 0.5 pixels and four more). As I wrote above, I will correct them in this resizing [task](https://github.com/mapbox/maki/issues/555). Therefore, this push now has 38 changed icons (I forgot about charging-station.svg and added it).

Screen Shot 2022-05-30 at 19 48 18


[LINK to the combining map](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sy2zmr000l14p7qi22t83d&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#13.89/37.76623/-122.42474)

Below are links to specific ones. But it's too much of them to test it on the map. I think a better way will be to check others in my [Figma file](https://www.figma.com/file/Ogqi7HpbVlr8yGw3ZrYL3g/Maki?node-id=524%3A12154)

May-30-2022 20-19-50


[Shops](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sz2ylm000315o3ar1avovr&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#18.89/37.7325017/-122.4902912)
Screen Shot 2022-05-30 at 20 00 34

[Fuel](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sz2ylm000315o3ar1avovr&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#20.21/37.756646/-122.5017323)
Screen Shot 2022-05-30 at 19 58 45

[Playground](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sz2ylm000315o3ar1avovr&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#18.76/37.7647491/-122.5050737)
Screen Shot 2022-05-30 at 19 57 29

[Restaurant-pizza](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sz2ylm000315o3ar1avovr&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#18.48/37.7533875/-122.497105)
Screen Shot 2022-05-30 at 19 59 37

[Mountain](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3ohokst002715mmy4t00g2o&right=mapbox://styles/udobnyi/cl3sz2ylm000315o3ar1avovr&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#16.09/37.901795/-121.939044)
Screen Shot 2022-05-30 at 20 04 32

**Review by tristen — APPROVED** [review]
🏅

**Pull request merged**
