### PR TITLE
Add the Viewpoint Icon

### PR DESCRIPTION
**Pull request by sarahmamy**
From issue #271 

11px
image

image

15px
image

image

### CODE REVIEW

**Comment by natslaughter** [comment]
@sarahmamy thanks for the PR and your interest in Maki.
Could you please provide existing examples as to how and where this viewpoint icon is used?

**Comment by sarahmamy** [comment]
Thanks Nathaniel :D
This icon could be used to show vista points or viewpoints, which are tagged in OSM as `tourism:viewpoint`. What I proposed is a standard way to indicate them on road signs. Alternatively, openstreetmap.org uses a binocular icon (image), but either way it does not exist in Maki yet.

A viewpoint in France on OSM --> https://www.openstreetmap.org/#map=19/48.90614/2.10303
Also found this article --> https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dviewpoint

**Comment by pathmapper** [comment]
@sarahmamy thanks for creating this icon!

@natslaughter more examples:

On all maps of this PDF ->
https://www.rwe.com/web/cms/mediablob/de/1761250/data/496148/5/rwe-power-ag/nachbarschaft/Wegweiser.pdf

Wikimedia:
https://commons.wikimedia.org/wiki/File:Pictograms-nps-misc-scenic_viewpoint.svg

**Comment by natslaughter** [comment]
closing here as the viewpoint icons will be merged in PR #437

**Pull request closed without merging**
