### PR TITLE
Grill icon

### PR DESCRIPTION
**Pull request by aparlato**
grill #276 for next Maki release.

cc @natslaughter

### CODE REVIEW

**Comment by aparlato** [comment]
Should we rename this `bbq` instead of `grill` before merging? Closest thing in Open Street Map is amenity=bbq.

[taginfo](http://taginfo.openstreetmap.org/tags/amenity=bbq)

[open street map wiki](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbbq)

**Comment by natslaughter** [comment]
@aparlato 
grill-11 could use a little massaging so that the pixels inside the grill legs where 100% white

screen shot 2017-01-02 at 2 11 22 pm

**Comment by aparlato** [comment]
Could that be an illustrator thing? It's showing up like this on my end.

image

**Comment by aparlato** [comment]
@natslaughter ok I just double checked, and everything seems to be fine in the branch from this morning. The bbq-11 you posted appears to be the old version prior to edits 2 weeks ago.

**Comment by nickidlugash** [comment]
@aparlato want to doublecheck some of the pixel alignment on both these icons, particularly the left side of the wheels, and the smoke lines? /cc @natslaughter 

image

**Comment by natslaughter** [comment]
@aparlato 
I just noticed one more pixel alignment issue in the 11-pixel bbq icon. 

screen shot 2017-01-03 at 11 56 36 am

Aligning the right grill leg to the pixel grid might change the leg angle, so you might have to change the left leg angle as well.

**Comment by natslaughter** [comment]
@aparlato I'm noticing some anchor points in both `bbq` icons that if deleted, do change the geometry, but don't really need to be there if the geometry is drawn correctly. You might want to redraw the "smoke" element to make the anchor point assembly more clean. 

screen shot 2017-01-03 at 12 33 52 pm

screen shot 2017-01-03 at 12 31 22 pm

cc @nickidlugash

**Comment by natslaughter** [comment]
@aparlato I'm still seeing some extraneous anchor point in these bbq icons, and after a talk with @nickidlugash, I'm responding with a larger issue/opportunity for Maki and using these particular icons as an example. 
I'm not sure why the 'smoke' part of the icon is so wonky. Probably my fault since I started the icon, but there is no reason why it shouldn't be created with basic, geometric shapes. This would remedy the extra anchor points and curve dissonance present in the shape. I quickly created this drawing sequence, which is tl:dr, but hopefully it is a start to something useful.

screen shot 2017-01-04 at 11 36 58 am

screen shot 2017-01-04 at 11 40 20 am


screen shot 2017-01-04 at 11 38 46 am


screen shot 2017-01-04 at 11 37 31 am

**Comment by nickidlugash** [comment]
@natslaughter great diagram :D Do you want to open up a separate ticket where we can continue to explore a kit of parts for Maki? 

@aparlato excited to hear your thoughts on this as you finish up this icon!

**Comment by natslaughter** [comment]
@aparlato 
Saw a few extraneous anchor points on the 15-pixel icon

screen shot 2017-01-05 at 1 49 29 pm

This should be it though!

**Pull request merged**
