### PR TITLE
Add stripclub icon.

### PR DESCRIPTION
**Pull request by christoph-buente**
This icon is for amenity=stripclub, see http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dstripclub

### CODE REVIEW

**Comment by morganherlocker** [comment]
no thank you

**Comment by a-di-na** [comment]
Sorry, @morganherlocker - can you please give us a short summary of what's wrong with the icon (for the designer)? Do you just don't want to add a stripclub icon or is it the design of the icon?

**Comment by jacksonj04** [comment]
The icon itself doesn't seem too clear, and I think it might be down to trying to incorporate the curves on (what I presume is) the woman. At smaller sizes it's just a collection of lines without definition (is it a broken gate? A chinese symbol?). I'm afraid I can't offer any thoughts on how to clarify it though.

I do, however, think that it shouldn't be excluded purely because it's an icon for a strip club. If someone has a use case for it then given there are already icons for logging sites, oil wells and polling places (all of which are actually pretty narrow use cases) and if a workable icon can be found I say go for it.

**Comment by christoph-buente** [comment]
Thx @jacksonj04 for the detailed feedback. Right now we try to collaborate with a bunch of designers. They are all good designers, but the concept of a vector graphic being mapped to virtual pixel boundaries seems to be very counter intuitive. We'll pass that feedback on. We have more in the pipeline, but this icon was the most promising one so far.

@morganherlocker Being against something without telling any reason has never been productive in any situation. The reason for this, and many more icons is, that we want to replace the current iconset on wheelmap.org with maki iconset. But there are about 30+ missing, and that's why we try to create them and by making them public let everybody participate from our work. As @jacksonj04 pointed out, there are a lot of niche icons, that don't apply to every map. That does not necessarily mean, that they are invalid per se.

**Comment by morganherlocker** [comment]
@christoph-buente Maki is meant to be a general purpose community iconset. Having tags like `striptease` or `lapdance` runs counter to this. People are free to map whatever they want, but age-inappropriate or offensive icons belong somewhere else.

**Comment by christoph-buente** [comment]
@morganherlocker thx for the feedback. Is there an official age-rating for this icon set? Or a code of conduct that we might need to adhere? Happy to do that but i did not find any on the MB maki page.
Or is this simply a kind of censorship? I mean does it make sense to rework this icon at all, or will it be rejected anyways?

**Comment by mikemorris** [comment]
I would generally be inclined to reject an icon like this which IMHO is coming from a position of objectifying a person or group, especially as something that may deter people from contributing to or using a project like Maki.

> logging sites, oil wells and polling places

This is a false equivalency, in that none of these markers convey an implicit bias and would be equally suitable for a logging/mining company mapping their sites as they would be to environmental activists.

**Comment by christoph-buente** [comment]
Hey @mikemorris,

we totally do not want to insult any person or group at all. In fact with http://wheelmap.org and the whole http://sozialhelden.de team is out there to fight for equality and inclusion. We'll do some brain storming to come up with an idea how an icon could look like in a nicer way.

Apart from that denying an icon does not make stripclubs go away. They're just part of our reality.

**Pull request closed without merging**
